### ISSUE TITLE
Is brickpi3-nodejs compatible with the older brickpi+?

### ISSUE THREAD

**Issue by giacecco** [byWulf/brickpi3-nodejs#1]
I am getting this trying to install on a vanilla, up-to-date install of raspbian for robots:

```
pi@brickpi:~/temp $ npm install --save brickpi3
/
> pi-spi@1.0.2 install /home/pi/temp/node_modules/brickpi3/node_modules/pi-spi
> node-gyp rebuild

make: Entering directory '/home/pi/temp/node_modules/brickpi3/node_modules/pi-spi/build'
  CXX(target) Release/obj.target/spi_binding/spi_binding.o
In file included from ../node_modules/nan/nan.h:199:0,
                 from ../spi_binding.cc:2:
../node_modules/nan/nan_maybe_pre_43_inl.h: In function ‘Nan::Maybe<bool> Nan::DefineOwnProperty(v8::Handle<v8::Object>, v8::Handle<v8::String>, v8::Handle<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_pre_43_inl.h:158:44: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
                  !(current & v8::ReadOnly) &&               // writable AND
                                            ^
In file included from ../spi_binding.cc:2:0:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:331:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
../spi_binding.cc: In member function ‘virtual void SpiTransfer::Execute()’:
../spi_binding.cc:61:50: warning: missing initializer for member ‘spi_ioc_transfer::tx_buf’ [-Wmissing-field-initializers]
                   struct spi_ioc_transfer msg = {};
                                                  ^
../spi_binding.cc:61:50: warning: missing initializer for member ‘spi_ioc_transfer::rx_buf’ [-Wmissing-field-initializers]
../spi_binding.cc:61:50: warning: missing initializer for member ‘spi_ioc_transfer::len’ [-Wmissing-field-initializers]
../spi_binding.cc:61:50: warning: missing initializer for member ‘spi_ioc_transfer::speed_hz’ [-Wmissing-field-initializers]
../spi_binding.cc:61:50: warning: missing initializer for member ‘spi_ioc_transfer::delay_usecs’ [-Wmissing-field-initializers]
../spi_binding.cc:61:50: warning: missing initializer for member ‘spi_ioc_transfer::bits_per_word’ [-Wmissing-field-initializers]
../spi_binding.cc:61:50: warning: missing initializer for member ‘spi_ioc_transfer::cs_change’ [-Wmissing-field-initializers]
../spi_binding.cc:61:50: warning: missing initializer for member ‘spi_ioc_transfer::tx_nbits’ [-Wmissing-field-initializers]
../spi_binding.cc:61:50: warning: missing initializer for member ‘spi_ioc_transfer::rx_nbits’ [-Wmissing-field-initializers]
../spi_binding.cc:61:50: warning: missing initializer for member ‘spi_ioc_transfer::pad’ [-Wmissing-field-initializers]
spi_binding.target.mk:82: recipe for target 'Release/obj.target/spi_binding/spi_binding.o' failed
make: *** [Release/obj.target/spi_binding/spi_binding.o] Error 1
make: Leaving directory '/home/pi/temp/node_modules/brickpi3/node_modules/pi-spi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.9.35+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/temp/node_modules/brickpi3/node_modules/pi-spi
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! pi-spi@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pi-spi@1.0.2 install script.
npm ERR! This is most likely a problem with the pi-spi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pi-spi
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.9.35+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "brickpi3"
npm ERR! cwd /home/pi/temp
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/temp/npm-debug.log
npm ERR! not ok code 0
pi@brickpi:~/temp $ 
```

**Comment by giacecco** [comment]
The problem may be easier, however I could not solve it. I am using your library on raspbian that is subject to this issue https://stackoverflow.com/a/21168305/1218376 . I have tried a few of the suggestions listed there but none worked for me.

**Comment by byWulf** [comment]
Hey, better late than never ^^'

This package should be compatible only with the brickpi3 and not with brickpi+ (its practically a port of the [brickpi3 python lib](https://www.dexterindustries.com/BrickPi/brickpi3-getting-started-step-4-program-brickpi-robot/brickpi3-getting-started-program-python/)).

You can find more information about programming the old BrickPi+ [here](https://www.dexterindustries.com/brickpi-tutorials-documentation/) and the corresponding Nodejs lib for it [here](https://www.npmjs.org/package/brickpi-raspberry).
